snapshots += Led::App::Snapshot
snapshot_headers += apps/led/app.h

app_objs += $(addprefix apps/led/,\
  app.o\
  main_controller.o\
)

i18n_files += $(addprefix apps/led/,\
  base.universal.i18n\
)

app_images += apps/led/led_icon.png
