snapshots += Brainfuck::App::Snapshot
snapshot_headers += apps/brainfuck/app.h

app_objs += $(addprefix apps/brainfuck/,\
  app.o\
  machine.o \
  execution_controller.o\
  editor_controller.o\
  input_controller.o\
  brainfuck_text_area.o\
)

i18n_files += $(addprefix apps/brainfuck/,\
  base.universal.i18n\
)

app_images += apps/brainfuck/brainfuck_icon.png
