snapshots += Nw2048::App::Snapshot
snapshot_headers += apps/nw_2048/app.h

app_objs += $(addprefix apps/nw_2048/,\
  app.o\
  game.o\
  tile.o\
  controller.o\
  game_view.o\
)

i18n_files += $(addprefix apps/nw_2048/,\
  base.universal.i18n\
)

app_images += apps/nw_2048/nw_2048_icon.png
