snapshots += Hello::App::Snapshot
snapshot_headers += apps/hello/app.h

app_objs += $(addprefix apps/hello/,\
  app.o\
  hello_controller.o\
  hello_view.o\
)

i18n_files += $(addprefix apps/hello/,\
  base.universal.i18n\
)

app_images += apps/hello/hello_icon.png
